apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: backend-cart
          image: harsh3305/hrv-mart-backend-cart
          ports:
            - containerPort: 8083
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodb_uri
                  name: secret
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: kafka-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cart-service
spec:
  selector:
    app: cart
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30003